services:
  db:
    image: postgres:18.4
    container_name: db_sales
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_DB: ${POSTGRE_DB}
    ports:
      - "5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

  backe_end:
    build: .
    restart: always
    container_name: backend_sales
    ports:
      - "5019:5000"
    env_file:
    - path: .env
      required: false

volumes:
  psql_data:
